### ISSUE TITLE
Ice home support

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice-builder-gradle#10]
If the `ICE_HOME` env variable or the `slice.iceHome` property isn't set, the builder will default `iceHome` to /usr or /usr/local on Linux/macOS platforms or the Ice installation directory on Windows (see README.md explanation).

To figure out `slice.jarDir` we check for the existence of the directories `<iceHome>/share/java`, `<iceHome>/java/lib` and finally `<iceHome>/lib`.

Because of this latest directory check, `slice.jarDir` always ends up being set to `/usr/lib` or `/usr/local/lib` if the other directories don't exist. Given that JAR files aren't expected to be stored in the lib directory, it would be better to set `slice.jarDir` to null in this case. Right now, `slice.jarDir` will never be null (contrary to what the documentation says).

**Comment by pepone** [comment]
Gord rid of `jarDir` property with #14
