### ISSUE TITLE
Execution failed for task ':test:compileSlice'.

### ISSUE THREAD

**Issue by kingwen8174** [zeroc-ice/ice-builder-gradle#2]
Hi:
 i build use source,then foud exception:

* What went wrong:
Execution failed for task ':test:compileSlice'.
> /opt/software/ice-require/ice-require/ice-3.6.3/cpp/bin/slice2java command failed: 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 2.576 secs
Stopped 0 compiler daemon(s).
Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':test:compileSlice'.] from daemon DaemonInfo{pid=7841, address=[71d17dfd-83b7-4b6e-9a05-a60e5c93d39a port:36590, addresses:[/0:0:0:0:0:0:0:1%1, /127.0.0.1]], idle=true, context=DefaultDaemonContext[uid=24659ea0-c311-42d7-ba73-563ca98569d8,javaHome=/opt/jdk7,daemonRegistryDir=/root/.gradle/daemon,pid=7841,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]}.

why?? who can help me?? thanks..

**Comment by externl** [comment]
Looks like you did not compile `slice2java`.  Does `/opt/software/ice-require/ice-require/ice-3.6.3/cpp/bin/slice2java` exist?
