### ISSUE TITLE
On Windows, default slice2java not found with 32-bit JDK

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice-builder-gradle#8]
Affects v1.4.6

When using a 32-bit JDK with a default Ice installation (C:\Program Files\ZeroC\Ice-3.7.x), the builder fails with the following error message:
```
A problem occurred evaluating script.
> slice2java (\bin\slice2java.exe) not found. Please ensure that Ice is installed and the iceHome property () is correct.
```
This occurs because:
- the builder looks for the default Ice installation in the Windows registry using the \\HKLM\SOFTWARE\ZeroC\Ice* keys
- with Ice 3.7.x, the MSI installer is a 64-bit installer that creates keys in \\HKLM\SOFTWARE\ZeroC\Ice* but not \\HKLM\SOFTWARE\WOW6432Node\ZeroC

Note that Ice 3.6 creates Windows registry entries in \\HKLM\SOFTWARE\WOW6432Node\ZeroC, so in 32-bit mode, the gradle plugin will find Ice 3.6 but not Ice 3.7 when iceHome/ICE_HOME is not set.

**Comment by pepone** [comment]
Fixed in 1.4.6 d9780d967bb93c3e439efcd20ded5a99ae330c14
